global: 
  env: dev
  secret: sealed-secret
  serviceaccount:
    aws_role_arn: ""
  ingress_service: frontend
  production_url: app.timeslotbooking.supplystack.com
  enable_tracing: false
  recaptcha_site: ""

########## JAVA Services ##########
api-gateway:
  create_service: true
  init_container_enabled: false
  port: 9190
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/api-gateway
    tag: replaceme

booking-service:
  create_service: true
  init_container_enabled: true
  port: 9096
  mem_limit: 1024Mi
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/booking-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD
  - AUTH0_M2M_CLIENT_SECRET

carrier-service:
  create_service: true
  init_container_enabled: true
  port: 9098
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/carrier-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD

customer-service:
  create_service: true
  init_container_enabled: true
  port: 9095
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/customer-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD
  - AUTH0_M2M_CLIENT_SECRET

grid-service:
  create_service: true
  init_container_enabled: true
  port: 9193
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/grid-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD

notification-service:
  create_service: true
  init_container_enabled: false
  port: 8080
  image: 
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/notification-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD
  - AUTH0_M2M_CLIENT_SECRET

onboarding-service:
  create_service: true
  init_container_enabled: true
  port: 9192
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/onboarding-service
    tag: replaceme
  extra_secrets:
  - DB_ANALYTICS_PASSWORD
  - KAFKA_PASSWORD
  - AUTH0_M2M_SB_ONBOARDING_CLIENT_SECRET

scheduler-service:
  create_service: true
  init_container_enabled: false
  port: 9195
  readiness_probe_path: /actuator/health/readiness
  liveness_probe_path: /actuator/health/liveness
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/scheduler-service
    tag: replaceme
  extra_secrets:
  - KAFKA_PASSWORD
  - AUTH0_M2M_CLIENT_SECRET
  - ZEEBE_CLIENT_SECRET
  - RECAPTCHA_SECRET

template-service:
  create_service: true
  init_container_enabled: true
  port: 9099
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/template-service
    tag: replaceme
  extra_secrets:
  - AUTH0_M2M_CLIENT_SECRET

########## Frontend ##########
frontend:
  create_service: true
  init_container_enabled: false
  mem_limit: 64Mi
  port: 8080
  user: 101
  group: 101
  fsgroup: 101
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/frontend
    tag: replaceme

