global: 
  env: dev
  enable_tracing: false
  platform: amd64
  secret: sealed-secret
  ingress_service: cint-service
  legacy_prod_url: carrierportal.slickss.io
  kafka:
    brokers: 01.kafka-broker.supplystack.io:9091,02.kafka-broker.supplystack.io:9091,03.kafka-broker.supplystack.io:9091
    schema_registry: https://01.schema-registry.supplystack.io:8081,https://02.schema-registry.supplystack.io:8081,https://03.schema-registry.supplystack.io:8081
    security_protocol: SASL_SSL
    sasl_mechanism: SCRAM-SHA-256

cint-service:
  create_service: true
  create_pdb: true
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/cint-service
  deployment_strategy: RollingUpdate
  replicas: 2
  mem_limit: 640Mi
  extra_secrets:
  - DD_API_KEY
  - DD_APP_KEY
  - DB_SERVICE_PASSWORD

cti-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/cti-service
  extra_secrets:
  - DB_CTI_PASSWORD
  - CTI_LIB_DB_PASSWORD

bas-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/bas-service
  extra_secrets:
  - DB_BAS_PASSWORD

db-schenker-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/db-schenker-service
  extra_secrets:
  - DB_DBSCHENKER_PASSWORD
  extra_env:
  - name: GEO_LOCATION_HOST
    value: http://geo-location-service:8080
  
dfds-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dfds-service
  extra_secrets:
  - DB_DFDS_PASSWORD

dhl-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dhl-service
  extra_secrets:
  - DB_DHL_PASSWORD

dhl-express-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dhl-express-service
  extra_secrets:
  - DB_DHLEXPRESS_PASSWORD

dpd-at-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-at-service
  extra_secrets:
  - DB_DPDAT_PASSWORD

dpd-be-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-be-service
  extra_secrets:
    - DB_DPDBE_PASSWORD

dpd-ch-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-ch-service
  extra_secrets:
  - DB_DPDCH_PASSWORD

dpd-de-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-de-service
  extra_secrets:
  - DB_DPDDE_PASSWORD

dpd-nl-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-nl-service
  extra_secrets:
  - DB_DPDNL_PASSWORD

dpd-seur-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dpd-seur-service
  extra_secrets:
  - DB_DPDSEUR_PASSWORD

dsv-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/dsv-service
  extra_secrets:
  - DB_DSV_PASSWORD

essers-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/essers-service
  extra_secrets:
  - DB_ESSERS_PASSWORD

fedex-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/fedex-service
  extra_secrets:
  - DB_FEDEX_PASSWORD

fleetboard-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/fleetboard-service
  extra_secrets:
  - DB_FLEETBOARD_PASSWORD

fleetvisor-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/fleetvisor-service
  extra_secrets:
  - DB_FLEETVISOR_PASSWORD

geo-location-service:
  create_service: true
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/geo-location-service

getru-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/getru-service
  extra_secrets:
  - DB_GETRU_PASSWORD

gvt-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/gvt-service
  extra_secrets:
  - DB_GVT_PASSWORD

heisterkamp-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/heisterkamp-service
  extra_secrets:
  - DB_HEISTERKAMP_PASSWORD

idealogistic-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/idealogistic-service
  extra_secrets:
  - DB_IDEALOGISTIC_PASSWORD

jost-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/jost-service
  extra_secrets:
  - DB_JOST_PASSWORD

kuehnenagel-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/kuehnenagel-service
  extra_secrets:
  - DB_KUEHNENAGEL_PASSWORD
  extra_env:
  - name: KUEHNENAGEL-SERVICE_SCHEDULER_CONSUMER_CRON
    value: 0 */5 * * * *

prevost-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/prevost-service
  extra_secrets:
  - DB_PREVOST_PASSWORD

project44-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/project44-service
  extra_secrets:
  - DB_PROJECT44_PASSWORD

satmars-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/satmars-service
  extra_secrets:
  - DB_SATMARS_PASSWORD

simulation-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/simulation-service
  extra_secrets:
  - DB_SIMULATION_PASSWORD

sls-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/sls-service
  extra_secrets:
  - DB_SLS_PASSWORD

tnt-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/tnt-service
  extra_secrets:
  - DB_TNT_PASSWORD

transics-service:
  create_service: true
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/transics-service
  extra_secrets:
  - DB_TRANSICS_PASSWORD

transsmart-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/transsmart-service
  extra_secrets:
  - DB_TRANSSMART_PASSWORD

transuniverse-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/transuniverse-service
  extra_secrets:
  - DB_TRANSUNIVERSE_PASSWORD

ups-service:
  image:
    repository: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/cint/ups-service
  extra_secrets:
  - DB_UPS_PASSWORD
  extra_env:
  - name: GEO_LOCATION_HOST
    value: http://geo-location-service:8080