kind: pipeline
name: helm
steps:

- name: fix-permissions
  image: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/drone/permission-fix

- name: helm-linter
  depends_on:
  - fix-permissions
  image: nexus.supplystack.io/alpine/helm:3.6.3
  user: 999:999
  environment:
    HOME: /drone/src  
  when:
    event:
    - push
    - pull_request
  commands:
  - |
    fail=0
    for i in */ ; do
      helm lint $i || fail=1
    done

    if [ $fail -gt 0 ] ; then
      echo 'Some charts failed linting!'
      exit 1
    fi

- name: chart-release
  depends_on:
  - helm-linter
  image: quay.io/helmpack/chart-releaser:v1.2.1
  user: 999:999
  environment:
    HOME: /drone/src
    CR_TOKEN: 
      from_secret: CR_TOKEN
  when:
    event:
    - push
    branch:
    - master
  commands:
  - git fetch origin +refs/heads/gh-pages
  - mkdir .cr-index
  # - wget -O .cr-index/index.yaml https://slick-dev.github.io/helm-charts-mdw/index.yaml
  - |
    for i in */ ; do
      cr package $i
    done
  - cr upload --owner slick-dev --git-repo helm-charts-mdw --skip-existing
  - cr index --owner slick-dev --git-repo helm-charts-mdw --charts-repo https://slick-dev.github.io/helm/ --push