apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.notification_service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.env "prod" }}
  replicas: 2
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.notification_service.name }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Values.notification_service.name }}.logs: '[{"service":"{{ .Values.notification_service.name }}", "source":"{{ .Values.notification_service.name }}"}]'
        ad.datadoghq.com/tags: '{"env": "{{ .Values.env }}", "service":"{{ .Values.notification_service.name }}", "source":"{{ .Values.notification_service.name }}"}'
        prometheus.io/scrape: "false"
        supplystack.io/env: {{ .Values.env }}
      labels:
        app.kubernetes.io/name: {{ .Values.notification_service.name }}
    spec:
      {{- if eq .Values.env "prod" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ .Values.notification_service.name }}
            topologyKey: failure-domain.beta.kubernetes.io/zone
      {{- end }}
      {{- if ne .Values.env "prod" }}
      {{- if eq .Values.platform "arm64" }}
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
      {{- else }}
      nodeSelector:
        lifecycle: Ec2Spot-m4-m5
      tolerations:
      - key: spotInstance
        operator: Equal
        value: tolerate
        effect: NoSchedule
      {{- end }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: {{ .Values.notification_service.name }}
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.notification_service.image.repository }}:{{ .Values.notification_service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
            value: "true"
          {{- if $.Values.enable_tracing }}
          - name: JAVA_TOOL_OPTIONS
            value: '-javaagent:/opt/opentelemetry-javaagent-all.jar'
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name={{ $.Values.env }}-{{ $.Chart.Name }}-{{ .Values.notification_service.name }},job={{ $.Values.env }}-{{ $.Chart.Name }}/{{ .Values.notification_service.name }}
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(HOST_IP):4317
          {{- end }}
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.env }}
          - name: CONSUL_ACL_TOKEN
            valueFrom:
              secretKeyRef:
                name: sealed-secret
                key: CONSUL_ACL_TOKEN
          - name: CONSUL_HOST
            value: consul-redirector.consul
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sealed-secret
                key: DB_PASSWORD
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sealed-secret
                key: KAFKA_PASSWORD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 512Mi
