---
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Chart.Name }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1875"   
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers 'Access-Control-Allow-Origin: $http_origin';
       more_set_headers 'Access-Control-Allow-Credentials: true';
spec:
  tls:
  - hosts:
    {{- if eq $.Values.global.env "prod" }}
    {{- if $.Values.global.url }}
    - {{ $.Values.global.url }}
    {{- else }}
    - {{ $.Values.global.customer }}.{{ $.Chart.Name }}.supplystack.com
    {{- end }}
    {{- else }}
    {{- if $.Values.global.url }}
    - {{ $.Values.global.url }}
    {{- else }}
    - {{ $.Values.global.customer }}.{{ $.Chart.Name }}.{{ $.Values.global.env }}.supplystack.com
    {{- end }}
    {{- end }}
    secretName: le-{{ $.Values.global.env }}-{{ $.Chart.Name }}-{{ $.Values.global.customer }}
  rules:
  {{- if eq $.Values.global.env "prod" }}
  {{- if $.Values.global.url }}
  - host: {{ $.Values.global.url }}
  {{- else }}
  - host: {{ $.Values.global.customer }}.{{ $.Chart.Name }}.supplystack.com
  {{- end }}
  {{- else }}
  {{- if $.Values.global.url }}
  - host: {{ $.Values.global.url }}
  {{- else }}
  - host: {{ $.Values.global.customer }}.{{ $.Chart.Name }}.{{ $.Values.global.env }}.supplystack.com
  {{- end }}
  {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: express
            port:
              name: http
        {{- else }}
        backend:
          serviceName: express
          servicePort: http
        {{- end }}
      - path: /socket
        {{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: socket
            port:
              name: http
        {{- else }}
        backend:
          serviceName: socket
          servicePort: http
        {{- end }}


