apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "analytics_service.labels" . | nindent 4 }}
  name: {{ .Values.analytics_service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: actuator
    port: 9090
    targetPort: actuator
  selector:
    app.kubernetes.io/name: {{ .Values.analytics_service.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "api_gateway.labels" . | nindent 4 }}
  name: {{ .Values.api_gateway.service_name_override }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: actuator
    port: 9090
    targetPort: actuator
  selector:
    app.kubernetes.io/name: {{ .Values.api_gateway.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: {{ .Chart.Name }}
    {{- if eq .Values.env "prod" }}
    consul.hashicorp.com/service-meta-url: {{ .Chart.Name }}.supplystack.com
    {{- else }}
    consul.hashicorp.com/service-meta-url: {{ .Chart.Name }}.{{ .Values.env }}.supplystack.com
    {{- end }}
    consul.hashicorp.com/service-meta-customer: supplystack
    consul.hashicorp.com/service-meta-env: {{ .Values.env }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
  name: {{ .Values.portal.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: actuator
    port: 9090
    targetPort: actuator
  selector:
    app.kubernetes.io/name: {{ .Values.portal.name }}
