{{- if Capabilities.APIVersions.Has networking.k8s.io/v1 }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "activity-service.labels" . | nindent 4 }}
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    {{- if eq .Values.env "prod" }}
    - {{ .Chart.Name }}.supplystack.com
    {{- else }}
    - {{ .Chart.Name }}.{{ .Values.env }}.supplystack.com
    {{- end }}
    secretName: le-{{ .Values.env }}-{{ .Chart.Name }}
  rules:
  {{- if eq .Values.env "prod" }}
  - host: {{ .Chart.Name }}.supplystack.com
  {{- else }}
  - host: {{ .Chart.Name }}.{{ .Values.env }}.supplystack.com
  {{- end }}
    http:
      {{- if Capabilities.APIVersions.Has networking.k8s.io/v1 }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.activity_service.name }}
            port:
              name: http
      {{- else }}
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.activity_service.name }}
          servicePort: http
      {{- end }}