cluster: changeme
image:
  tag: v0.25.1
  repository: docker.io/grafana/agent
logs:
  url: https://logs-prod-eu-west-0.grafana.net/api/prom/push
  username: 160683
metrics:
  url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  username: 323426
traces:
  endpoint: tempo-eu-west-0.grafana.net:443
  username: 157193
statefulset:
  nodeSelector: {}
  tolerations: []
