
{{- range $service, $config := .Values }}
{{- if ne $service "global" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $service }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/version: {{ $config.image.tag }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ $service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service }}
  {{- if or ( eq $.Values.global.env "staging" ) ( eq $.Values.global.env "prod" ) }}
  replicas: {{ $config.replicas | default 2 }}
  {{- else }}
  replicas: {{ $config.replicas | default 1 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if eq $service "frontend" }}
        fluentbit.io/parser: nginx
        {{- end }}
        supplystack.io/env: {{ $.Values.global.env }}
        prometheus.io/scrape: 'false'
        ad.datadoghq.com/tags: '{"env": "{{ $.Values.global.env }}", "service":"slotbooking", "source":"{{ $service }}"}'
        ad.datadoghq.com/{{ $service }}.logs: '[{"service":"slotbooking", "source":"{{ $service }}"}]'
      labels:
        app.kubernetes.io/name: {{ $service }}
    spec:
      {{- if eq $.Values.global.env "prod" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ $service }}
            topologyKey: failure-domain.beta.kubernetes.io/zone
      {{- end }}
      serviceAccountName: {{ $.Chart.Name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ $config.user | default 65534 }}
        runAsGroup: {{ $config.group | default 65534 }}
        fsGroup: {{ $config.fsgroup | default 65534 }}
      automountServiceAccountToken: false
      enableServiceLinks: false
      {{- if ne $.Values.global.env "prod" }}
      nodeSelector:
        lifecycle: Ec2Spot-m4-m5
      tolerations:
      - key: spotInstance
        operator: Equal
        value: tolerate
        effect: NoSchedule
      {{- end }}
      {{- if $config.init_container_enabled }}
      initContainers:
      - name: init-container-service
        image: 748094632676.dkr.ecr.eu-west-1.amazonaws.com/slotbooking/init-container:{{ $config.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: APPLICATION
        - value: slotbooking
        - name: SERVICE
        - value: {{ $service }}
        - name: CONSUL_ACL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: CONSUL_ACL_TOKEN
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $.Values.global.env }}
        - name: CONSUL_HOST
          value: {{ $.Values.global.consul_host | default "consul-redirector.consul" }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: DB_PASSWORD
        {{- range $config.extra_secrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ $service }}
        image: {{ $config.image.repository }}:{{ $config.image.tag }}
        securityContext:
          allowPrivilegeEscalation: false
        {{- if $config.create_service }}
        ports:
        - name: http
          containerPort: {{ $config.port }}
        {{- end }}
        env:
        - name: CONSUL_ACL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: CONSUL_ACL_TOKEN
        {{- if ne $service "frontend" }}
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        - name: SPRING_PROFILES_ACTIVE
          value: {{ $.Values.global.env }}
        {{- end }}
        - name: CONSUL_HOST
          value: {{ $.Values.global.consul_host | default "consul-redirector.consul" }}
        {{- if and ( ne $service "frontend" ) ( ne $service "api-gateway" ) }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: DB_PASSWORD
        {{- end }}
        {{- if eq $service "frontend" }}
        - name: DIST_FOLDER
          value: dist/apps/slotbooking
        - name: STAGE
          value: {{ $.Values.global.env }}
        - name: SB_CONTEXT
          value: slotbooking
        {{- end }}
        {{- if eq $service "scheduler-service" }}
        - name: RECAPTCHA_SITE
          value: {{ $.Values.global.recaptcha_site }}
        - name: ZEEBE_WORKFLOW_PREFIX
          {{- if $config.zeebe_workflow_prefix }}
          value: {{ $config.zeebe_workflow_prefix }}
          {{- else }}
          value: {{ $.Values.global.env }}-slotbooking
          {{- end }}
        {{- end }}
        {{- if and ( ne $service "frontend" ) ( $.Values.global.enable_tracing ) }}
        - name: JAVA_TOOL_OPTIONS
          value: '-javaagent:/opt/opentelemetry-javaagent-all.jar'
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name={{ $.Values.global.env }}-{{ $.Chart.Name }}-{{ $service }},job={{ $.Values.global.env }}-{{ $.Chart.Name }}/{{ $service }}
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(HOST_IP):4317
        {{- end }}
        {{- range $config.extra_secrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret }}
              key: {{ . }}
        {{- end }}
        {{- range $config.extra_env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        resources:
          requests:
            cpu: 100m
            memory: {{ $config.mem_limit | default "512Mi" }}
          limits:
            memory: {{ $config.mem_limit | default "512Mi" }}
        readinessProbe:
          httpGet:
            path: {{ $config.readiness_probe_path | default "/actuator/health" }}
            port: {{ $config.port }}
        livenessProbe:
          httpGet:
            path: {{ $config.liveness_probe_path | default "/actuator/health" }}
            port: {{ $config.port }}
          {{- if eq $.Values.global.env "prod" }}
          initialDelaySeconds: 600
          {{- else }}
          initialDelaySeconds: 1200
          {{- end }}
{{- end }}
{{- end }}
