
{{- range $service, $config := .Values }}
{{- if and ( ne $service "global" ) ( eq $service $.Values.global.ingress_service ) }}
---
{{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ $.Release.Namespace }}
  name: ingress-default
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 3m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    {{- if eq $.Values.global.env "prod" }}
    - {{ $.Values.global.production_url }}
    {{- else }}
    - {{ $.Chart.Name }}.{{ $.Values.global.env }}.supplystack.com
    {{- end }}
    secretName: le-{{ $.Values.global.env }}-{{ $.Chart.Name }}
  rules:
  {{- if eq $.Values.global.env "prod" }}
  - host: {{ $.Values.global.production_url }}
  {{- else }}
  - host: {{ $.Chart.Name }}.{{ $.Values.global.env }}.supplystack.com
  {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ $service }}
            port:
              name: http
        {{- else }}
        backend:
          serviceName: {{ $service }}
          servicePort: http
        {{- end }}
{{- end }}
{{- end }}

#
# Extra URL
#
{{- range $service, $config := .Values }}
{{- if and ( ne $service "global" ) ( eq $service $.Values.global.ingress_service ) }}
{{- range $.Values.global.extra_urls }}
---
{{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{ $.Release.Namespace }}
  name: ingress-{{ .  | replace "." "-" }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ $.Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 3m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ . }}
    secretName: le-{{ $.Values.global.env }}-{{ $.Chart.Name }}-{{ .  | replace "." "-" }}
  rules:
  - host: {{ . }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ $service }}
            port:
              name: http
        {{- else }}
        backend:
          serviceName: {{ $service }}
          servicePort: http
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
