apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if $.Values.global.serviceaccount.aws_role_arn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.global.serviceaccount.aws_role_arn }}
  {{- end }}