---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-daemonset
  namespace: {{ $.Release.Namespace }}
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      name: agent-daemonset
  template:
    metadata:
      labels:
        name: agent-daemonset
      annotations:
        supplystack.io/env: cluster
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        - -config.expand-env
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: sealed-secret
              key: API_KEY
        - name: CLUSTER
          value: {{ .Values.cluster }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 4317
          hostPort: 4317
          name: otlp-grpc
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/agent
          name: agent-daemonset
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/machine-id
          name: etcmachineid
          readOnly: true
        - mountPath: /tmp/grafana-agent/positions
          name: positions
        - mountPath: /tmp/grafana-agent/wal
          name: wal
      serviceAccount: grafana-agent
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - configMap:
          name: agent-daemonset
        name: agent-daemonset
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - hostPath:
          path: /etc/machine-id
        name: etcmachineid
      - hostPath:
          path: /tmp/grafana-agent/positions
        name: positions
      - hostPath:
          path: /tmp/grafana-agent/wal
        name: wal
  updateStrategy:
    type: RollingUpdate