apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portal.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.env "prod" }}
  replicas: {{ .Values.portal.replicas | default 2 }}
  {{- else }}
  replicas: {{ .Values.portal.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.portal.name }}
  template:
    metadata:
      annotations:
        fluentbit.io/parser: nginx
        ad.datadoghq.com/{{ .Values.portal.name }}.logs: '[{"service":"{{ .Chart.Name }}", "source":"{{ .Values.portal.name }}"}]'
        ad.datadoghq.com/tags: '{"env": "{{ .Values.env }}", "service":"{{ .Chart.Name }}", "source":"{{ .Values.portal.name }}"}'
        supplystack.io/env: {{ .Values.env }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '9090'
      labels:
        app.kubernetes.io/name: {{ .Values.portal.name }}
    spec:
      {{- if eq .Values.env "prod" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ .Values.portal.name }}
            topologyKey: failure-domain.beta.kubernetes.io/zone
      {{- end }}
      {{- if ne .Values.env "prod" }}
      nodeSelector:
        lifecycle: Ec2Spot-m4-m5
      tolerations:
      - key: spotInstance
        operator: Equal
        value: tolerate
        effect: NoSchedule
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: {{ .Values.portal.name }}
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: actuator
              containerPort: 9090
          env:
          - name: DIST_FOLDER
            value: dist/apps/carrier-portal
          - name: STAGE
            value: {{ .Values.env }}
          - name: CONTEXT
            value: carrier-portal
          - name: CONSUL_ACL_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret }}
                key: CONSUL_ACL_TOKEN
          - name: CONSUL_HOST
            value: consul-redirector.consul
          - name: MANAGEMENT_PORT
            value: 9090
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
