---
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    {{- if eq .Values.env "prod" }}
    - {{ .Chart.Name }}.supplystack.com
    - {{ .Chart.Name }}-service.supplystack.com
    {{- else }}
    - {{ .Chart.Name }}.{{ .Values.env }}.supplystack.com
    - {{ .Chart.Name }}-service.{{ .Values.env }}.supplystack.com
    {{- end }}
    secretName: le-{{ .Values.env }}-{{ .Chart.Name }}
  rules:
  {{- if eq .Values.env "prod" }}
  - host: {{ .Chart.Name }}.supplystack.com
  {{- else }}
  - host: {{ .Chart.Name }}.{{ .Values.env }}.supplystack.com
  {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.portal.name }}
            port:
              name: http
        {{- else }}
        backend:
          serviceName: {{ .Values.portal.name }}
          servicePort: http
        {{- end }}
  {{- if eq .Values.env "prod" }}
  - host: {{ .Chart.Name }}-service.supplystack.com
  {{- else }}
  - host: {{ .Chart.Name }}-service.{{ .Values.env }}.supplystack.com
  {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.service_name_override }}
            port:
              name: http
        {{- else }}
        backend:
          serviceName: {{ .Values.service.service_name_override }}
          servicePort: http
        {{- end }}
